services:
  angula:
    container_name: angula
    image: angula
    build: .
    environment:
      DABABASE_URL: "host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}